services:
    apache:
        image: php:8.5-apache
        build:
            context: ./php
        ports:
            -   "8080:80"
        volumes:
            -   ./app:/var/www/html/
        depends_on:
            -   mysql

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: tp1004AM
            MYSQL_DATABASE: tp-10-04-AM
            MYSQL_USER: johnny
            MYSQL_PASSWORD: johnny7791
        ports:
            -   "3306:3306"
        volumes:
            -   ./mysql:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin
        ports:
            -   "8081:80"
        environment:
            PMA_HOST: mysql
            PMA_PASSWORD: tp1004AM
        depends_on:
            -   mysql

    postgresql:
        image: bitnami/postgresql
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: sondageRdc
        ports:
            - "5432:5432"
        volumes:
            - ./postgres:/bitnami/postgresql

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@1004.am
            PGADMIN_DEFAULT_PASSWORD: 1004am
        ports:
            -   "8082:80"
        depends_on:
            -   postgresql

    mail_hog:
        image: mailhog/mailhog
        logging:
            driver: 'none'
        ports:
            -   "1025:1025"
            -   "8025:8025"
        

    